# -*- coding: utf-8 -*-
"""board.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lsTOIdXlk7FvY4Rw70b-GGvQwFIOF-g0
"""

board = ["_","_","_"]
for i in range(3):
  print(board)